import { Banner } from "../../components/Banner";
import { ModelInsights } from "../../components/ModelInsights";

export const Home = () => {
  return (
  <div className="flex flex-col space-y-2">
    <Banner
      heading={"Content based recommendation modelling"}
      className="h-[80vh] md:h-[60vh] lg:h-[50vh] px-5 md:px-5 lg:px-20 "
    >
      <div className="">
          <p>
            Content-based recommendation filter is used to recommend products similar to those
            being clicked, liked or purchased by user. User recommendations is based on the description of the product
            and profile of the user&apos;s interests.
          </p>
          <p>
            Content-based recommender systems can be used in an e-commerce platforms. It is one of the basic algorithms in a recommendation
            engine. Content-based filtering can be triggered for any event; for example, on click, on purchase, or add to cart.
          </p>
          <p>
            For an e-commerce platform, the product&apos;s page can show recommendations generated by this algorithm 
            in the “related products” section.
          </p>
        </div>
      </Banner>
      <ModelInsights name={"TF-IDF"}/>
  </div>);
};
